#!/usr/bin/env bash

# name of current directory
CURRENT_FOLDER="$(basename `eval pwd`)"
# directory inside vagrant
DIR="~/Code/${CURRENT_FOLDER}"

# Server ip address
# By default the homested server ip is 192.168.10.10
SERVER_IP="192.168.10.10"

# Server Username
# By default the homestead username is vagrant
USER_NAME="vagrant"
# CONSTANTS WITH SETTINGS TO ACCESS VAGRANT
CMD="ssh ${USER_NAME}@${SERVER_IP}"
# registers the ssh key in your system
env=~/.ssh/agent.env

agent_load_env () { test -f "$env" && . "$env" >| /dev/null ; }

agent_start () {
    (umask 077; ssh-agent >| "$env")
    . "$env" >| /dev/null ; }

agent_load_env

# agent_run_state: 0=agent running w/ key; 1=agent w/o key; 2= agent not running
agent_run_state=$(ssh-add -l >| /dev/null 2>&1; echo $?)

if [ ! "$SSH_AUTH_SOCK" ] || [ $agent_run_state = 2 ]; then
    agent_start
    ssh-add
elif [ "$SSH_AUTH_SOCK" ] && [ $agent_run_state = 1 ]; then
    ssh-add
fi

unset env


# If any arguments passed...
if [ $# -gt 0 ]; then

    #get info from .env file
    if [ -f .env ]; then
        source .env
    fi


    # Access to artisan command on the project folder
    # short form 'art'
    if [ "$1" == "artisan" ] || [ "$1" == "art" ]; then
        shift 1
        $CMD "cd $DIR && php artisan `echo "$@"`"


    # Access to composer command on the project folder
    # short form 'comp'
    elif [ "$1" == "composer" ] || [ "$1" == "comp" ]; then
       shift 1
        $CMD  "cd $DIR && composer `echo "$@"`"


    # Access to phpunit on the project folder
    # short form 'p'
    elif [ "$1" == "test" ] || [ "$1" == "phpunit" ]; then
        shift 1
        $CMD  "cd $DIR && ./vendor/bin/phpunit `echo "$@"`"

    # Access to phpunit --filter command on the project folder
    # short form 'pf'
    elif [ "$1" == "pf" ] || [ "$1" == "filter" ]; then
        shift 1
        $CMD  "cd $DIR && ./vendor/bin/phpunit --filter `echo "$@"`"

    # Access to artisan db:seed command on the project folder
    elif [ "$1" == "seed" ]; then
        shift 1
        $CMD  "cd $DIR && php artisan db:seed `echo "$@"`"

    # Access to npm command on the project folder
    elif [ "$1" == "npm" ]; then
       shift 1
        $CMD  "cd $DIR && npm `echo "$@"`"

    # Run npm watch
    elif [ "$1" == "watch" ]; then
       shift 1
        $CMD  "cd $DIR && npm run watch-poll"

    # Access to artisan migrate command on the project folder
    elif [ "$1" == "migrate" ]; then
        shift 1
        $CMD  "cd $DIR && php artisan migrate `echo "$@"`"

    # Get dump of db to dump.sql file that will be created on the project folder
    elif [ "$1" == "dump" ]; then
        shift 1
        $CMD  "cd $DIR && mysqldump $DB_DATABASE > dump.sql"

    # Creates a db for you based on the DB_DATABASE set on .env file
    elif [ "$1" == "create:db" ]; then
        shift 1
        $CMD  " mysql -u homestead -p -e \"create database $DB_DATABASE; GRANT ALL PRIVILEGES ON testedb TO homestead\" "

    #if you don't know what you doing 404 ;)
    else
        echo "Command Not Found 404 ERROR :)"
    fi
# if nothing is passed the artisan commands hint will be shown
else
    $CMD " cd $DIR && php artisan `echo "$@"`"
fi
